[project]
name = "my-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.44.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "openai>=1.102.0",
    "pypdf2>=3.0.1",
]
